/**
 * Aegis core — signals, scope and context: the first sections of aegis.js, without the DOM engine.
 * Generated by build.mjs from aegis.core.js; the types themselves live in aegis.d.ts.
 *
 * @version 0.7.2
 * @license MIT
 */

export type * from './aegis.js';
export {
    AegisWarning,
    batch,
    computed,
    createContext,
    createScope,
    defaults,
    deferred,
    dev,
    effect,
    flush,
    getOwner,
    inject,
    isSignal,
    onDispose,
    onError,
    onWarn,
    provide,
    root,
    runWithOwner,
    signal,
    signals,
    startTransition,
    trace,
    transaction,
    trusted,
    untrack,
    useScheduler
} from './aegis.js';
